### ISSUE TITLE
Run test in local failed but in github is success

### ISSUE THREAD

**Issue by sieusaya149** [hikijs/Blog_Backend#66]

**Comment by sieusaya149** [comment]
FAIL   BLOG_PROJECT  tests/post/getPosts.test.js (6.755 s)
  APIs Create Post
    User Did Not Publish Post Before
      ✓ user read their post success (48 ms)
    User Had Published Some Posts
      ✕ Each User read their post success (1934 ms)
      ✕ Other Can View Public Post (2134 ms)
      ✕ Friend Can View Public And Follower Post (1378 ms)

  ● APIs Create Post › User Had Published Some Posts › Each User read their post success

    expect(received).toEqual(expected) // deep equality

    Expected: 0
    Received: 3

      197 |                     const result = await dbInstance.hitQuery(getPostQuery);
      198 |                     // ensure that there is no post in the db
    > 199 |                     expect(result.length).toEqual(0);
          |                                           ^
      200 |                     // reset the public Infor
      201 |                     overviewPost.cleanUp();
      202 |             });

      at Object.toEqual (tests/post/getPosts.test.js:199:26)

  ● APIs Create Post › User Had Published Some Posts › Other Can View Public Post

    expect(received).toEqual(expected) // deep equality

    Expected: 6
    Received: 7

      300 |                                     'public'
      301 |                             );
    > 302 |                             expect(numberPosts).toEqual(
          |                                                 ^
      303 |                                     overviewPost.getTotalPublicPosts() - numPublicPostOfUser2
      304 |                             );
      305 |                             expect(numberPosts).toEqual(listPost.length);

      at Object.toEqual (tests/post/getPosts.test.js:302:25)

  ● APIs Create Post › User Had Published Some Posts › Other Can View Public Post

    expect(received).toEqual(expected) // deep equality

    Expected: 0
    Received: 3

      197 |                     const result = await dbInstance.hitQuery(getPostQuery);
      198 |                     // ensure that there is no post in the db
    > 199 |                     expect(result.length).toEqual(0);
          |                                           ^
      200 |                     // reset the public Infor
      201 |                     overviewPost.cleanUp();
      202 |             });

      at Object.toEqual (tests/post/getPosts.test.js:199:26)

  ● APIs Create Post › User Had Published Some Posts › Friend Can View Public And Follower Post

    expect(received).toEqual(expected) // deep equality

    Expected: 16
    Received: 17

      384 |                                     'all'
      385 |                             );
    > 386 |                             expect(numberPosts).toEqual(
          |                                                 ^
      387 |                                     numsTotalPostOfUser2 +
      388 |                                             numsPublicPostOfUser3 +
      389 |                                             numsPublicPostOfUser1 +

      at Object.toEqual (tests/post/getPosts.test.js:386:25)

  ● APIs Create Post › User Had Published Some Posts › Friend Can View Public And Follower Post

    expect(received).toEqual(expected) // deep equality

    Expected: 0
    Received: 3

      197 |                     const result = await dbInstance.hitQuery(getPostQuery);
      198 |                     // ensure that there is no post in the db
    > 199 |                     expect(result.length).toEqual(0);
          |                                           ^
      200 |                     // reset the public Infor
      201 |                     overviewPost.cleanUp();
      202 |             });

      at Object.toEqual (tests/post/getPosts.test.js:199:26)

Test Suites: 1 failed, 2 passed, 3 of 5 total
Tests:       3 failed, 4 passed, 7 total
Snapshots:   0 total
Time:        26.446 s
Ran all test suites.

Failed 3 testcase
